apiVersion: v2
name: msa-hw4
description: Helm-чарт для приложения User Service HW4
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "16.6.7"
  repository: "oci://registry-1.docker.io/bitnamicharts"
  alias: postgresql
  condition: postgresql.enabled
  
- name: ingress-nginx
  version: "4.12.2"
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: ingress-nginx.enabled