apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-hw4-app-config
  namespace: msa-hw4-ns
data:
  POSTGRES_HOST: "postgresql-db"
  POSTGRES_DB: "msa_hw4_db"
  APP_PORT: "5000"
  DATABASE_URL_TEMPLATE: "postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"
    